
version: "3"
services:
  company-api:
    build: .
    container_name: company-api
    working_dir: /company-api
    volumes:
      - .:/company-api
    ports:
      - "8000:8000"
    links:
      - mysql
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_DATABASE=blog
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
